Update lib
opensourceways/robot-gitee-openeuler-review pull request #9
Opened 2022-01-20 08:25 UTC by xwz123

2022-01-20 08:30 UTC, xwz123 commented on lgtm.go
> +	if commenter := e.GetCommenter(); e.GetPRAuthor() != commenter {
s/commenter := e.GetCommenter(); e.GetPRAuthor() != commenter/e.GetCommenter() != e.GetPRAuthor()

2022-01-20 08:30 UTC, xwz123 commented on permission.go
> +	sdk "github.com/opensourceways/go-gitee/gitee"
fmt import

2022-01-21 01:50 UTC, zengchen1024 requested changes

2022-01-21 01:50 UTC, zengchen1024 commented on lgtm.go
> +	if v := getLGTMLabelsOnPR(e.GetIssueLabelSet()); len(v) > 0 {
check it

2022-01-21 01:58 UTC, wanghao75 commented on permission.go
>  func (bot *robot) isRepoOwners(
isRepoOwners 这个地方是不是不需要了，判断仓库的OWNERS文件，除了community有，其他的库也没有OWNERS文件

2022-01-21 02:02 UTC, xwz123 commented on permission.go
>  func (bot *robot) isRepoOwners(
The goal of this PR is to upgrade the library version without making functional changes

2022-01-21 02:18 UTC, merged